# ConfigurationServer module configuration

server:
  port: 9999
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/petrov/programming/non_work/dailyplanner/configurationserver/src/main/resources/config/dailyplanner
